"""add teacher media files table

Revision ID: 06eb64206f65
Revises: f990ef2f35a5
Create Date: 2025-05-30 23:11:35.524368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06eb64206f65'
down_revision: Union[str, None] = 'f990ef2f35a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('media_file_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'resources', 'teacher_media_files', ['media_file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.drop_column('resources', 'media_file_id')
    # ### end Alembic commands ###
