"""add_credits_and_department_to_subjects

Revision ID: 2e1dcffebdd5
Revises: 72d0b65247c7
Create Date: 2025-06-22 20:50:14.180906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e1dcffebdd5'
down_revision: Union[str, None] = '72d0b65247c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('credits', sa.Integer(), nullable=True))
    op.add_column('subjects', sa.Column('department', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'department')
    op.drop_column('subjects', 'credits')
    # ### end Alembic commands ###
