"""fix_teacher_media_files_foreign_key

Revision ID: 9b2036524ad7
Revises: 06eb64206f65
Create Date: 2025-05-30 23:30:25.111684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b2036524ad7'
down_revision: Union[str, None] = '06eb64206f65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('teacher_media_files_teacher_id_fkey', 'teacher_media_files', type_='foreignkey')
    op.create_foreign_key(None, 'teacher_media_files', 'users', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher_media_files', type_='foreignkey')
    op.create_foreign_key('teacher_media_files_teacher_id_fkey', 'teacher_media_files', 'professors', ['teacher_id'], ['id'])
    # ### end Alembic commands ###
